name: Build Wheelhouse

on:
  workflow_dispatch:
  release:
    types: [published]
  # during debugging
  # push:
  #   branches:
  #     - wheelhouse

jobs:
  build-wheelhouse:
    name: wheelhouse-${{ matrix.python-version }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.12"
            architecture: "x64"
            runs_on: "windows-latest"
          # - python-version: "3.12"
          #   architecture: "x86"
          #   runs_on: "windows-latest"
          # - python-version: "3.12"
          #   architecture: "arm64"
          #   runs_on: "windows-11-arm"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"

      - name: Upgrade build tools
        run: uv pip install --system --upgrade build wheel

      - name: Read package version from pyproject.toml
        id: pkg
        shell: pwsh
        run: |
          $version = python -c "import pathlib, tomllib; print(tomllib.loads(pathlib.Path('pyproject.toml').read_text(encoding='utf-8'))['project']['version'])"
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Download dependency wheels
        run: |
          mkdir build\wheels
          python -m pip download -r requirements.txt -d build\wheels --only-binary=:all:

      - name: Build and copy project wheel and requirements
        run: |
          python -m build --wheel --outdir build\wheels
          copy requirements.txt build

      - name: Create zip archive
        shell: pwsh
        run: |
          $zipName = "wheelhouse-${{ steps.pkg.outputs.version }}-py${{ matrix.python-version }}-${{ matrix.architecture }}.zip"
          Compress-Archive -Path build\* -DestinationPath $zipName

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: wheelhouse-${{ steps.pkg.outputs.version }}-py${{ matrix.python-version }}-${{ matrix.architecture }}
          path: wheelhouse-${{ steps.pkg.outputs.version }}-py${{ matrix.python-version }}-${{ matrix.architecture }}.zip

      # Attach to GitHub Release (only if triggered by release)
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: wheelhouse-${{ steps.pkg.outputs.version }}-py${{ matrix.python-version }}-${{ matrix.architecture }}.zip
